name: PlanetReego
version: ${project.version}
main: org.jayjaytee.planetreego.PlanetReego
authors: [ JAYJAYTEE ]
description: An open-source Spigot plugin for the Minecraft server PlanetReego
website: mc.reego.org
